name: RDP-Windows

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok & NSSM
      run: |
        Invoke-WebRequest https://drive.google.com/uc?id=1rOcmv_d7FEdWZaJbxn_05aQxmlWaEUQ_  -OutFile ngrok.exe
        Invoke-WebRequest https://drive.google.com/uc?id=1FR2OSfwq8KvATlgcHtDQbarLYCwidfqd  -OutFile nssm.exe
    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
     env:
        NGROK_AUTH_TOKEN: ${1s2JM69JogbqSWa0qPLTYK3vSiJ_2P5wGAixJ7LaVuyAAbRJy}
      - name: Connect your NGROK account
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      
    - name: Download Important Files.
      run: |
        Invoke-WebRequest https://drive.google.com/uc?id=1REWL1Vhd88bDBOSsXvV0OTdYAkcIgGXH  -OutFile NGROK-AP.bat
        Invoke-WebRequest https://drive.google.com/uc?id=1glLBT3jp5uGD_0lmE20kiWyr84v79w0F  -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://drive.google.com/uc?id=1FhT889-R8wIQ5LqYRyGDQO6rLr9w8Ox3  -OutFile loop.bat
    - name: Make YML file for NGROK.
      run: start NGROK-AP.bat
    - name: Enable RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel
      run: sc start ngrok
    - name: Connect to your RDP CPU 2 Core - 7GB Ram - 255 SSD.
      run: cmd /c NGROK-CHECK.bat
    - name: All Done! You can close Tab now! Maximum VM time:6h.
      run: cmd /c loop.bat
